name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        # Poniższa linia zostanie dodana, aby wykluczyć wersję 3.10 dla systemu ubuntu
        exclude-versions: 3.10

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install flake8 and unittest
      run: |
        python -m pip install flake8
        # unittest jest częścią standardowej biblioteki Pythona, więc nie musisz go instalować oddzielnie

    - name: Display Python version
      run: python --version

    - name: Run flake8
      run: |
        flake8 .

    - name: Run unit tests
      run: |
        python -m unittest discover
