name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        exclude-versions: 3.10  # Wykluczenie wersji 3.10 dla systemu ubuntu

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install flake8 and unittest
      run: |
        python -m pip install flake8
        python -m pip install unittest

    - name: Display Python version
      run: python --version

    - name: Run flake8
      run: |
        flake8 .

    - name: Run unit tests
      run: |
        python -m unittest discover
